version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting Docker build..."
      - docker --version

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t my-ecs-api:latest .

  post_build:
    commands:
      - echo "Docker image build completed successfully."
      - docker images